# Generated by Django 5.1 on 2024-09-05 16:50

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=101)),
                ('slug', models.CharField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(default='defaults.jpg', upload_to='images/')),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('english', 'english'), ('french', 'french'), ('Hhindi', 'hindi'), ('german', 'german')], default='bangla', max_length=100)),
            ],
        ),
    ]
