# Generated by Django 5.1 on 2024-09-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
