# Generated by Django 5.1 on 2024-09-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_data_age_alter_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='firstapp/images'),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
