# Generated by Django 5.1 on 2024-09-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_data_image_alter_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Teacher', max_length=100),
        ),
    ]
