# Generated by Django 5.1 on 2024-09-10 08:42

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_data_slug_alter_data_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('english', 'english'), ('german', 'german'), ('hindi', 'hindi'), ('arabi', 'arabi'), ('urdu', 'urdu')], default='bangla', max_length=100),
        ),
    ]
