# Generated by Django 5.1 on 2024-09-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=17)),
                ('content', models.TextField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sluck', models.CharField(default=models.CharField(max_length=100), max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('details', models.TextField()),
                ('status', models.BooleanField()),
                ('category', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=100)),
            ],
        ),
    ]
